name: .NET Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install Targeting Pack
      run: dotnet targeting-pack install net480
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish DelvUIPlugin.csproj -c Release -o DelvUIPlugin
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: DelvUIPlugin
        path: DelvUIPlugin/**
        if-no-files-found: error